import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-light min-h-screen  "}>
        {children}
        <div className="h-32 bg-side-dark text-white  flex justify-center items-center  mt-80">
          <div className="text-side-light-text cursor-pointer">
            <Link href={"https://github.com/mscankat/movie-search-app"}>
              GitHub
            </Link>
          </div>
        </div>
      </body>
    </html>
  );
}
